language: node_js
node_js:
- 12.10.0
dist: trusty
script:
- cd /home/travis/build/jdmac020/goodaleHeadsUp-rest/goodale-heads-up-rest/
- npm install
- npm test
deploy:
  provider: heroku
  api_key:
    secure: bntfhhtp5XiCRTZUL+7tdtW9VL34j7L37bbpghYmaRIzEBcFi8BlXniHduJcwuSd8D1xtTYJ1YEdEWyI+pBR6uAmro4gLz3PeoLvO+cga/eK1Kd5iSYzOXxyGL5g9GSnWBuI16fTJy/texg38E9P59/FBK15mqenLcT1htmqhhdHexW1kuiHpspadciCnYRuV/ke2I+lM9ltpzH6RZR94SxYqiilVOzP9gGnpSBelwGaGMME5lY9chqj5fc0wLBB97ktTB4F+vtTCmajMHx2ccQpUgawlWn3PzCVVqdZUO6Rlm+31emWC2cW+4Gp+MK99lMqidmSXU1Inx4VSQOmTTT/wcfQ158Xo/Qa/vgN2VqWj7hkkjXgnVNlilxLN0LFz8QjtQdpn3sGjQvpbnoln9Fp69uS9laUbZ53bI/rLc81VCCQr3R4aJoEImIcv5yoZkqKgoP7BGQtMvlIaehcsOv90D/wKHkdhqTf6Z/EYyVc2BS6gT9X/XwdRDRBjAY/kq7iwUCKr4TKDZJOvnxHIA2MhUwoWK8qRuXgWGWe+XDvcSPUVj+JzVXC4uTml7jbnaYXOtjK//TRiVUUQPZq8f1rnu8OOU2fu0+tVERwciHx3QZ5DGC9cTLdZM6YweZ2XT/PP+GOMjxaWFaijMCWaB18vuXzYAGobzmmAdzPHZw=
